export const variables = {
    page: 0,
    amountOfElements: 10,
    initialValue: 0,
    finalValue: 10,
    selectNumberValue: 10,
    currentMovieArray: [],
    movieArrayRendering: [],
    filteredArrayOfMovies: [],
    arrayNumberOfElements: [10, 15, 25],
    filter: false,
    arrayOfGenres: [
        "All genres",
        "Drama",
        "Horror",
        "Thriller",
        "Science-Fiction",
        "Action",
        "Crime",
        "Music",
        "Mystery",
        "Supernatural",
        "Adventure",
        "Family",
        "Medical",
    ],
    arrayOfLanguages: [
        "All languages",
        "English",
        "Japanese",
        "Spanish",
        "French",
        "Dutch",
        "German",
        "Portuguese",
        "Danish",
        "Swedish",
        "Korean",
        "Welsh",
        "Norwegian",
        "Italian",
        "Russian",
        "Thai",
        "Turkish",
        "Hungarian",
        "Ukrainian",
        "Polish",
    ],
};
